lunchclass/absolute

- scripts/get_nodejs_bin
- scripts/get_platform_bin
- scripts/run
script for downloding nodejs binary for linux platform. 
This patch does not support downloading windows because currently we can not unzip file on win-bash
> Add downloading nodejs binary for platform

- scripts/run
- server/package.json
After this patch, we no longer need re-execute our run.cmd manually.
> Use nodemon to support auto-reload when something is changed.

- server/package.json
Applied nodemon in the #56 patch but it breaks run.cmd. This CL is fixing it.
> Fix a regression after applying nodemon.

- bootstrap/common/sync_third_party.sh
When syncing node js binary on windows, especially, when extracting zip file
after downloading, too long path errors occurs. Currently, we are using $TMP
directory(in general the directory path is C:\Users\{NAME}\AppData\Local\Temp),
but it's too long basically. So, this CL is changing it to shorten path instead.
> Fix a bug when syncing node js binary on windows.

- bootstrap/absolute.sh
- bootstrap/command/node
- bootstrap/command/npm
We are using win-bash but the shell can not recognize and execute *.cmd files.
So, add some commands to bootstrap to execute and use the same commands in each
other platforms.
> Add npm and node commands which is platform independent.

- absolute.cmd
- bootstrap/absolute.sh
There was a problem when running absolute.cmd in Windows because of script path setting.
So I discussed it with romandev then modified scripts to fix this issue.
> Fix a bug when running absolute.cmd in Windows

- package.json
- "latest" keyword for gulp-nodemon occurs error when npm update and list
> Bug fix when calling npm update or list for gulp-nodemon package

- .travis.yml
The bot error occurs because |platform_test| is broken. We are trying to fix
the error(#228 by Wuseok@) currently and disable the test for the time being
in order to avoid bot error until the fix is landed.
> Disable |platform_test| for the time being in order to avoid bot error.

- .travis.yml
We introduced a new bootstrap test instead of legacy platform_test in #242. But
the test is still disabled in travis. So, enables the test in travis for test
automation to ensure that it works well in all platforms.
> Add bootstrap_test to travis.

- appveyor.yml
- bootstrap/test/test-start.js
This pull request is adding support for Windows test bot using AppVeyor.
Also, this CL is fixing bootstrap_test errors on Windows platform.
ISSUE=#139
> Add support for Windows test bot using AppVeyor.

- .appveyor.yml
- .travis.yml
The |branch| update test bots are triggered when target branch is updated.
(including temporary branch to send a pull request) But it can be overkill
because there are already |pull request| update test bots. We don't need to
have duplicated test bots the same pull request. So, add white-lists to block
other branches except master branch.
> Only allows |branch| update test bots on master branch.

- package.json
- server/server.js
When declaring multiple imports, a sorted list of import declarations make it
easier for developers to read the code and find necessary imports later.
> Add sort-imports rule.

- package.json
- server/worker_manager.js
We are using 2-space indentation but there is no rule in our lint configuration.
Related link:
http://eslint.org/docs/rules/indent
> Add |indent| rule to our lint.

- package.json
There was no declaration for |mongoose| in the dependencies entry in
package.json.
It can cause like the following error:
Error: Cannot find module 'mongoose'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (absolute/out/server/server.js:15:17)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
> Fix a regression after #283.

- package.json
- server/config.js
- server/https_server/https_server.js
- server/https_server/redirect_server.js
- server/server.js
We wanted to stop using commonjs style such as require() but there is no lint
rule to force it. To resolve the issue, we add |no-commonjs| rule by introducing
eslint-plugin-import[1].
[1] https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-commonjs.md
> Add |no-commonjs| rule by introducing eslint-plugin-import.

- .travis.yml
This is fixing travis bot error after #308 change.
> Override install section in .travis.yml for disabling default |npm install|.

- gulpfile.babel.js
This change is for Issue #264.
Any error message did not show although babel-build is failed
> Print babel error

- server/worker_manager.js
client.isWoker is wrong. client.isWorker is correct.
> Error on worker managers

- gulpfile.babel.js
- package.json
- server/config.js
- server/database.js
- server/https_server/https_server.js
- server/https_server/redirect_server.js
- server/push/controllers/send_push.js
- server/server.js
- server/worker_manager.js
This patch provides source map support for stack traces in node.
It uses the source-map module to replace the paths and line numbers of source-mapped files with their original paths and line numbers. The output mimics node's stack trace format with the goal of making every compile-to-JS language more of a first-class citizen. Source maps are completely general (not specific to any one language) so you can use source maps with multiple compile-to-JS languages in the same node process.
> Apply sourcemap to server (about Issue #300)

- package.json
- server/base/access_modifier.js
- server/example/example.js
Currently, latest ECMA standard can not support access modifiers such as
private, public and protected. However, sometimes they are useful for
perspective of readability. So, this change is providing decorators that can be
used similar to access modifiers. Please see example.js attached to this patch.
> Introduce access modifier decorator.

- client/push/push_key.js
- gulpfile.babel.js
- server/push/controllers/send_push.js
- server/push/gen_push_key.js
- server/push/push_key.js
- server/push/push_key.json
- vapidkeys generate before building client and server
- vapid public key needed by client and private key must not visible
- to remove readfile from json, changes to javascript file has json data exported
- GeneratePushKey function generates vapid keys and write json data as javascript code
> Generate vapid keys on absolute start in gulp

- gulpfile.babel.js
"build_client" command returns error that couldn't find preset es2015 because
that preset is removed in Introduce access modifier decorator. (#348)
so I made build_client command using the preset es2015-without-strict.
> fix the issue of build_client failure

- README.md
The bot links have been broken since moving repository to lunchclass.
> Fix broken links in README.md.

- CODEOWNERS
There will be a lot of pull requests in each modules but we don't have enough
owners for review process. So, we make the following people become temporary
owners to digest each module reviews. They are not official owners who are
nominated by official process but are much contributing to each modules.
So, we believe that they can take responsibility for each modules.
> Add @JayChl, @coconutperm, @nadongguri to CODEOWNERS.

- CODEOWNERS
In the file, oder is important. The last matching pattern takes the most
precedence. So, before this patch, Global Owner could not have a permission
other module directories. Please see this link[1].
[1] https://help.github.com/articles/about-codeowners/
> Fix an order of owner list in CODEOWNERS file.

- client/push/push_manager.js
- client/service-worker-manager.js
- Use vapid public key instead of using sender_id of manifest.json used by gcm
> Register applicationServerKey to subscribe

- gulpfile.ts
- package.json
This patch imports TypeScript modules and then introduce gulpfile.ts to replace
gulpfile.babel.js. Until finishing this migration, we can use the following
command to run gulpfile.ts.
$ ./absolute --gulpfile gulpfile.ts <command>
> Initial codes for typescript.

- CODEOWNERS
There will be a lot of pull requests in each modules but we don't have enough
owners for review process. So, we make the following people become temporary
owners to digest each module reviews. They are not official owners who are
nominated by official process but are much contributing to each modules.
So, we believe that they can take responsibility for each modules.
> Add @daehyunjimmy to CODEOWNERS.

- gulpfile.ts
- package.json
For this issue, I add run-sequence package to package.json file.
```
"run-sequence":"^2.2.0"
```
And then, I modify default task in gulpfile.ts
```
gulp.task('default', () => {
runSequence('build_server', 'run_server');
});
```
ISSUE=#461
> Fix Absolute V2 first launch fail issue.

- gulpfile.ts
We do not set callback for default task.
default task is finished after call run sequence.
For this reason, we get task logs like below:
```
[03:50:01] Starting 'default'...
[03:50:01] Starting 'build_server'...
[03:50:01] Finished 'default' after 28 ms
[03:50:02] Finished 'build_server' after 861 ms
[03:50:02] Starting 'run_server'...
[03:50:02] Finished 'run_server' after 51 ms
```
So I add callback function for waiting for run_server task
After this PR, we can see task logs like below:
```
[03:50:01] Starting 'default'...
[03:50:01] Starting 'build_server'...
[03:50:02] Finished 'build_server' after 861 ms
[03:50:02] Starting 'run_server'...
[03:50:02] Finished 'run_server' after 51 ms
[03:50:01] Finished 'default' after 912 ms
```
Please refer to
[run …
> Add callback for default task

- gulpfile.ts
- package.json
- server/base/application.ts
- server/example/example.router.ts
- tslint.json
After this patch, we can use the following commands:
$ ./absolute lint
$ ./absolute lint:fix
Also, this patch is fixing some lint errors that we can fix using
'lint:fix' automatically. On the other hand, the unresolved errors will
be fixed step by step in follow-up patch. Once resoloving the remaining
errors, we will be able to integrate the lint test with CI tools.
ISSUE=#465
> Apply tslint for linting TypeScript.

- gulpfile.ts
- package.json
- tsconfig.json
Currently, the configuration is hardcoded in gulpfile.ts. It's not bad
but one problem is that the configuration doesn't apply to gulpfile.ts.
ISSUE=none
> Separate configuration for TypeScript from gulpfile.ts

- gulpfile.ts
- package.json
- server/base/application.ts
- server/example/example.test.ts
- tsconfig.json
In Absolute v2, one of the most important things is unit test. So, we
introduce jest for module unit tests. After this patch, we can run test
as follows:
$ ./absolute test
Also, this change is adding an example test in server/example/.
ISSUE=none
> Introduce jest for module unit tests.

- AUTHORS
- client/index.html
- client/manifest.json
- server/base/application.test.ts
- server/base/application.ts
- I added client path and index.html / manifest.json files.
- Manifest info can check through below url after run server :
`http://127.0.0.1:8090/manifest.json`
- But currently manifest has minimal information only 
`eg. no launcher image, no gcm_sender_id...`
- Web app will not installed yet because that without service worker. 
ISSUE=#469
> Add client path and web app manifest

- AUTHORS
- server/server.ts
JSDoc should start with "/**" but current comment start with "/*"
ISSUE=#467
> Change comment in /server/server.ts to match JSDoc

- .appveyor.yml
- .travis.yml
- gulpfile.ts
- package.json
- server/base/application.test.ts
- server/base/application.ts
- server/example/example.router.ts
- server/example/example.test.ts
- server/server.ts
- tsconfig.json
- tslint.json
This change fixes all lint errors in the current implementation and then
enable lint test by default in Travis and AppVeyor to prevent unexpected
behaviors and errors.
ISSUE=#467
> Enable lint test by default in Travis and AppVeyor

- AUTHORS
- bootstrap/absolute.sh
- bootstrap/common/sync_third_party.sh
Upgrade Node.js (v6.9.5 -> v8.9.1)
ISSUE=#518
> Upgrade Node.js (v6.9.5 -> v8.9.1)

- server/base/application.ts
- server/example/example.router.ts
- server/example/example.test.ts
Add bodyParser Module and Test
It is needed for handling a request of post
ISSUE=#458
> Add bodyParser

- AUTHORS
- bootstrap/absolute.sh
- bootstrap/common/sync_third_party.sh
This reverts commit aecd7a943e0360db223438109d40cc9182bd7d06.
Revert reasons:
The change breaks AppVeyor build.
ISSUE=#518,#531
> Revert "Upgrade Node.js (v6.9.5 -> v8.9.1) (#520)"

- bootstrap/common/sync_third_party.sh
- bootstrap/common/util.sh
If script fail to download node binary, it should stop
and print right error log. This patch do it.
Additionally this patch add one function to print red color error log.
ISSUE=none
> Handle errors about third party download and extract
