server/app.js
It occur server internal exception when user connect server due to not
included render module on our project.
So I remove line for rendering.
=> Fix server exception issue.

scripts/get_nodejs_bin, scripts/util
Current implementation doesn't support for Mac OS yet. So, this patch is
implementing it and then adding some utility functions for it.
Also, this patch is fixing some of typos in existing codes.
=> Fix a bug that the run.cmd is failed on Mac OS.

server/app.js
ALL of Http-request is automatically converted to  Https-request
=> Redirect Http-request to Https

.gitignore
Want to ignore platform related files and node_modules.
=> Add .gitignore file to our repository.

scripts/run, server/package.json
1. Add forever package.
2. Running the node using forever
=> Run node server in background using forever package.

client/push/fcm.js
- fcm.register()
- fcm.unregister()
=> Register firebase push connection

scripts/get_nodejs_bin, scripts/path_info, scripts/platform_info, scripts/run
We need download node platform and unzip specific path.
=> Download node platform and unzip

scripts/get_mongodb_bin
=> Mongo db 32bit script

.gitignore
We don't need add npm-debug file.
=> Add npm-debug files to ignore

client/push/fcm.js
=> Request permission to create FCM token and send it to server

.gitignore, .travis.yml, absolute, absolute.cmd, bootstrap/absolute.sh, bootstrap/command/help, bootstrap/command/platform_test, bootstrap/command/start, bootstrap/command/stop, bootstrap/common/path_info.sh, bootstrap/common/platform_info.sh, bootstrap/common/string_util.sh, bootstrap/common/sync_third_party.sh, bootstrap/common/util.sh, bootstrap/test/assert.sh, bootstrap/test/platform_test.sh, server/package.json
=> Refactor scripts for bootstrap.

.travis.yml, bootstrap/common/sync_third_party.sh, bootstrap/common/util.sh
The travis system doesn't recognize negative return value. So, this CL is
changing the values to positive values. Also, simplifying progresses of
downloading and extracting.
=> Fix bootstrap scripts for travis test.

absolute.cmd, bootstrap/common/path_info.sh
This is a regression after #73.
=> Fix a bug when absolute runs on windows.

absolute, absolute.cmd, bootstrap/absolute.sh, bootstrap/command/help, bootstrap/command/node, bootstrap/command/npm, bootstrap/command/platform_test, bootstrap/command/start, bootstrap/common/path_info.sh, bootstrap/common/platform_info.sh, bootstrap/common/sync_third_party.sh, bootstrap/common/util.sh
This CL allows to run the bootstrap command in any path.
=> Introduce ASOLUTE_PATH envrionment variable.

.eslintrc, .gitignore, .travis.yml, bootstrap/command/lint, server/config.js, server/https_server/https_server.js, server/https_server/redirect_server.js, server/package.json, server/server.js
Add lint command and use it in travis test. Also, this CL is fixing many lint
errors from existing files. This CL is based on @nadongguri's CL(#68).
=> Add lint command and use it in travis test.

bootstrap/absolute.sh, bootstrap/common/path_info.sh, githooks/pre-commit
Add githooks directory and pre-commit command. The pre-commit command will
run 'lint' basically before committing patch.
=> Introduce git-hooks in client side.

bootstrap/command/start
When running the server, we want to set CWD to server/ directory.
=> Fix a regression after moving the package.json to project root path.

githooks/pre-commit
added --fix option in pre-commit.
=> add --fix option in pre-commit

package.json
=> Remove nodemon module

bootstrap/command/start_db, bootstrap/command/start_server, bootstrap/command/stop_db, bootstrap/command/stop_server
=> Forever start id.

client/device/camera/camera.js
Add API to control user mobile camera device.
- static resetOrientation( ) : Set correct image orientation.
- static getOrientation( ) : Get orientation value from captured image.
- public setImage( ) : Set image from camera.
=> Add API to control user mobile camera device.

githooks/pre-commit
- deleted --fix option for our development envirionment
=> delete --fix option in pre-commit

server/order/model/order.js, server/order/router/order_router.js, server/server.js
We need rest api for order menu.
https://{address}/api/order (POST)
=> Add rest api for order menu.

server/order/controller/order_controller.js, server/order/router/order_router.js
we need get ordered_list api and implement it.
=> Implement get ordered_list api

client/index.html, client/push/sw_manager.js, client/sw.js
- implementation of unregister API
- handle push request in Service Worker
=> Implementation of unregister API and handle push request

bootstrap/command/lint
fixed lint command for development envirionment
=> fixed absolute lint issue

client/order/order.js
=> Add order-api in client

client/device/camera/camera.js
Implementation of Camera API - resetOrientation function (Issue number #105 )
- static resetOrientation function : Set correct image orientation.
- change camera api name.
=> Implementation of Camera API - resetOrientation function.

client/deeplink/deeplink.js, client/index.html
Implement deep link to open an external browser.
KakaoTalk is using internal WebView to open link.
But we can't hand service worker and related features.
So, when we open link in kakao talk, we need to open link using chrome or sbrowser.
BUG=https://github.com/romandev/absolute/issues/96
=> Implement deep link to open an external browser.

client/deeplink/deeplink.js, client/wedding/index.html
resubmitted missing index.html file for wedding
=> recommit missing index.html for wedding

bootstrap/common/util.sh
Fix fail to wget download caused by ssl-exception
=> Ignore SSL Exception

client/device/camera/camera.js
This function get orientation value from image.
Issue#105
=> Implementation of getOrientation function.

server/db/db_connect.js
Change name to absolute from test(default)
=> Change database name

server/authorization/router/uuid_router.js, server/db/db_connect.js, server/order/controller/order_controller.js, server/order/controller/product_controller.js, server/order/router/order_router.js, server/order/router/product_router.js, server/push/controller/push_controller.js
Change variable name, and rest api changed(order, product)
=> Arrange code

server/order/controller/order_controller.js, server/order/controller/product_controller.js, server/order/router/order_router.js, server/order/router/product_router.js
Check product name and amount.
=> Refacor api

client/device/camera/camera.js
1. getImageFromCamera( ) : Get image from user camera app.
=> Implementation of camera api - getImageFromCamera function.

server/server.js
Json-length needs to be resizing because it makes 413 Error (Too large of pay load)
=> Resize limit of json-length

client/push/sw_manager.js
- Add getPushToken call to get current subscribe push token
- remove duplicated service worker register call
=> Add getPushToken call to get current subscribe push token

client/order/order.js
Syntax:
order(OrderInfo);
Pramemeter:
OrderInfo {
userId: String,
items: OrderItem or Array[OrderItem,...],
blob: Blob,
option: String,
}
OrderItem {
name: String,
count: Number,
amount: Number,
}
Return:
Promise
resolve(e), reject(e)
e: error_code (0: SUCCESS, 1: ERROR)
}
Description:
Send order to server and recieve error_code
=> API: order()

client/deeplink/deeplink.js, client/index.html
Deeplink should be sent when users are using android phone.
We blocked sending deeplink when users are using the others phones.
BUG=#96
=> Deeplink should be sent when users are using android phone.

client/push/sw_manager.js
- get uuid to verify user when send push token to server
=> Get uuid to verify user when send push token

client/push/sw_manager.js
=> Modify logic to get user id

client/push/sw_manager.js, server/server.js
This patch includes the following things.
- Fix a typo in the sw_manager.js: s/nadonguri.com/nadongguri.com
- Fix a lint error in the server.js
=> Fix a typo and a lint error.

client/device/camera/camera.js, client/index.html, client/order/orderui.js
1. Add api to control order page.
=> Implemention of order page api

client/sw.js
This change is for wedding. 
Before applying new implementation getting notification data by user id, use static message
=> use static message if notification data is not exist

client/authorization/authorization.js
cause: serviceworker cannot use localstorage in browser
=> Replace localStorage to IndexedDb

client/device/camera/camera.js, client/order/orderui.js
Camera & order UI api update
1. bug fix - onchange event does not called on input tag.
2. Apply order UI background color.
=> Camera & order UI api update

client/authorization/authorization.js, client/sw.js
- service worker gets push notification message from server with it's uuid if payload is not available
- authorization.js uses fetch instead of xhr because service worker can not use xhr
=> Add getting push notification message from server

client/authorization/authorization.js
- Exception occur while Object
- Remove unnecessary josn parsing line
=> Fix not generating uuid

client/authorization/authorization.js
- '=>' not allowed on old browser
=> Fix error on some old version browser

server/order/controller/order_controller.js
Get All of orderList
/api/order
=> GET All of orderList

client/order/order.js, package.json, server/order/router/order_router.js
Description:
return Array of imagePath(static)
Usage:
orderList(uuid).then(function(list) {
...
});
=> Syntax: orderList(uuid)

client/order/orderui.js
1. Move down the order page.
2. Change the button color.
3. Increase the button size.
=> Modify Order UI

client/order/order.js, server/order/controller/order_controller.js
Two changes:
1. JSON.stringfy is not neccessary to response for clients (already Json type)
2. Find only necessary field and response when client request query for image
=> Fixed performence issue

client/device/camera/camera.js
1. reduce the sumnail image size
=> Bug fix - Camera api performace issue

server/push/controller/push_controller.js, server/push/controller/push_notification.js, server/push/router/push_router.js
usage
userId : all
to api/push/notification post payload
=> Add broadcast push API for registered client

client/sw.js, server/order/controller/order_controller.js, server/order/router/order_router.js, server/push/controller/push_controller.js, server/push/controller/push_notification.js, server/push/router/push_router.js
- coupon image and uuid must be set before calling orderFinish
Add date comparing in service worker for coupon page
pushController.setPushNotificationMessage 호출 전, coupon image와 uuid mapping 이 필요함
=> Add orderFinish API to set coupon meesage and send push

client/order/order.js, server/order/router/order_router.js, server/push/controller/push_controller.js
Changes
1. Handle if push data and token could be null.
2. Handle if multi part form data could fail to be stored to server normally.
3. Fix options property did not sent to server.
=> Fix bug issue

client/order/order.js
Cause
Promise did not return anythings
=> Fix Bug of sendImage

client/device/camera/camera.js
=> Chage to public camera api.

client/sw.js, server/order/controller/coupon_controller.js, server/order/controller/order_controller.js, server/order/router/order_router.js, server/push/controller/push_notification.js
- features will work only after dday
- GET,  api/order/coupon?userId=${userId}
will return "order/coupon/${couponName}
=> Add coupon_controller for coupon API

client/sw.js
=> Modify Date for wuseok's wedding

server/push/controller/push_notification.js
- payload of json name changes to "data" from notification
=> Fix push is not working vibrate and url message

client/index.html
modified img path and title for Wuesok's wedding.
=> fix the issue that showing other wedding img on kakaotalk

client/sw.js
add wedding & coupon icons to sw notification
=> add icon to sw notification

server/order/controller/coupon_controller.js
change server d-day for wedding day(coupon)
=> change server d-day for wedding

server/database.js, server/https_server/https_server.js, server/https_server/redirect_server.js
fix error by valid-jsdoc option.
=> ESlint error fix in server folder

bootstrap/absolute.sh
solve this issue calling "npm update"
=> Bug fix gulp: command not found when running absolute start

bootstrap/common/sync_third_party.sh
trap command update argument so last command excute only
so tmp directory does not be removed.
=> Bug fix in sync_third_party( )

package.json, server/server.js
- With body-parser we can parse incomming request
=> Apply body parser to server

server/server.js
The lint error was caused by #227 change.
=> Fix a lint error in server.js.

bootstrap/absolute.sh
it solves [issue#218](https://github.com/romandev/absolute/issues/218)
=> update npm when package.json is changed

server/worker_manager.js
It's about issue #241 (Node.js should use multi cores.)
worker_manager.js will make children processes for load-balancing by using cluster module.
=> Add worker_manager for clustering

bootstrap/common/path_info.sh, githooks/pre-commit
this is related issue #272 
- stop using git-hooks.
- remove githooks directory and then remove related codes in bootstrap.
=> Remove git-hooks and related code.

package.json, server/config.js, server/push/controllers/send_push.js
- Need to generate vapid for first execution #286
- Need to get server vapid public key #287 
- Need to make testcase #285
=> Add sendPush function using web-push for payload encryption

gulpfile.babel.js, server/config.js, server/push/controllers/send_push.js, server/push/gen_push_key.js, server/push/push_key.json, server/server.js
- Move push related key to push_key.json
- Generate push vapid key at first launching server
=> Add generating push vapid key

bootstrap/test/test-update.js
Following issue #270
I added to check npm update module.
I try to test Windows and Linux.
Please check it
=> Check npm update module was added in bootstrap test

.gitattributes
It causes another problems that changes all end of line on Linux/Mac.
Not sure but it always makes some changes on git stage.
=> Revert "Add git attributes  (#334)"

AUTHORS
The file has a list of all contributors for Absolute.
=> Introduced AUTHORS.md file.

gulpfile.babel.js, package.json, server/base/application.js, server/example/router/example.router.js
The Application class is a wrapper class to hide server backend implementation.
In our Absolute project, we are currently using the Express but might want to
change the backend to other things. Even if so, we can change them smoothly.
This change is introducing a new way to route requests. We can refer to the
related example in server/example/router/example.router.js.
=> Implement Application class.

client/app.js, client/product/product.js
1. Product class define for user product
2. MandatoryOption, AdditionalOption class define for product option
=> client product class define

server/base/application.js
After this patch, we no longer access to private members outside of this class.
=> Apply access modifier decorator to application.js.

server/base/application.js, server/server.js
- server needs to setup client path and utilities to use
- add static path / body-parser initialization / mongoose connection
=> Add setup() method to Application

client/push/push_key.js, server/push/push_key.js
- No need to newly generated vapid for developement
- Vapid re-generation required when project published
=> Use generated push vapid for project

server/push/controller/send_push.js, server/push/router/push.router.js
- add router for push using Application.route
- use push_key instead of config
=> Add PushRouter using Application.route

gulpfile.babel.js, package.json
There was a mission to handle undefined tasks running as default.
I implemented that feature in node module then published it.
([https://github.com/nadongguri/gulp-undef-task-to-default])
=> unknown command goes to default

gulpfile.babel.js
I fix various ESLint errors in the file. 
(camelcase, semicolon, comma dangle, brace style, indentation)
=> Apply the ESlint rule to 'gulpfile.babel.js'

client/push/notification_manager.js, client/service-worker.js
* create Push notification when service worker got push event
* handle onclick event listener on push notification
=> handle push notification event in service worker

.gitignore
Add '.babel-cache.json' in '.gitignore'
=> Ignore babel-cache.json

AUTHORS
=> updated AUTHORS file with my details

server/push/controller/send_push.js, server/push/router/push.router.js
- POST /api/push/ now accept query userId
- Send push to registered userId using endpoint / push keys
=> Add api to sending push with userId registered

client/push/push_manager.js
- push subscription's getKey() api returns Uint8Array.
- convert subscription to json and send it.
=> Add json converted push keys to send push keys to server

client/app.ts, client/index.html, gulpfile.babel.js, package.json, tsconfig.json
After this patch, app.ts will build by typescirpt compiler and webpack so bundle_type.js will create in out path.
=> typescript apply in client build sequence

AUTHORS, server/push/test/test_push.js, server/worker_manager.js
In order to participate in this project, I am going to insert a patch that just fix typo in the code.
It is a simple modification, but I hope you will remember that it is the beginning.
Please review it. :+1:
=> Fix typo issue

gulpfile.ts, package.json, server/base/application.ts, server/example/example.router.ts
This is re-implementing #345 change in TypeScript.
ISSUE=#458
=> Remplement application framework in TypeScript.

docs/contributing.md
This documents covers contributing codes to absolute repository.
ISSUE=#459
=> Add contribution guide to docs.

server/base/application.ts, server/example/example.router.ts, server/server.ts, tslint.json
I fix typescript lint error.
ISSUE=#467
=> Fix Typescript Lint error basic.

server/example/example.router.ts
Fix tslint error more.
ISSUE=#467
=> Fix tslint error in example.router.ts

AUTHORS, tsconfig.json
I sorted the tsconfig.json file alphabetically.
ISSUE= #477
=> Sort tsconfig.json file in alphabetical order

AUTHORS, README.md
I've corrected the grammar in the readme.md file.
=> Grammar correction in the README.md file

AUTHORS, server/base/application.ts, server/example/example.router.ts, server/example/example.test.ts, server/server.ts
Fixed the function names and variable names in the server directory.
ISSUE=#467
=> Fix lint errors in server directory

docs/contributing.md
I translated 'contributing.md' into english. If there are any awkward parts, please point out.
=> Translated contributing.md

docs/contributing.md
I've made a few changes in the docs/contributing.md file.
ISSUE=none
=> Grammatical changes to contributing.md file

client/src/service_worker.ts, client/src/service_worker_controller.ts, tsconfig.json, webpack.config.ts
This is the basic work for a service worker.
Some interface should be declared for typescript.
This makes service worker related APIs can be called on TS.
ISSUE=none
=> Basic work for a service worker on typescript dev environment

bootstrap/common/sync_third_party.sh
Corrected the comment.
ISSUE=none
=> Fix the typo in bootstrap/common/sync_third_party.sh

client/notification/notification.test.ts, client/notification/notification_manager.ts, client/push/push_manager.ts
This is an initial implementation to provide notification APIs to
client app. The APIs always return false right now and we can implement
them later.
ISSUE=none
=> Implement skeleton codes for Notification APIs

docs/contributing.md
Change one of duplicated function to bar() from foo() in example.
ISSUE=none
=>  Fix wrong example in contributing.md

gulpfile.ts, package.json
Applied the mongo daemon startup option to 'gulpfile.ts'.
ISSUE=#503
=> Add new gulp task to 'gulpfile.js' for running mongo daemon

client/indexeddb/indexeddb.test.ts, client/indexeddb/indexeddb.ts
- The `set` method of `indexeddb` returns a boolean.
- I put the parameters in the test codes.
ISSUE=none
=> Fixed some errors of indexeddb

client/main.ts, client/push/push_manager.ts
Implemented unregister function for push api.
ISSUE=none
=> Implement unregister for Push API

client/push/push_service_worker.ts
Remove the reference tag in push_service_worker.ts.
It makes some trouble when running webpack to build.
ISSUE=#526
=> Fix a build error

CODEOWNERS
@nadongguri has been contributing Absolute project for a long time.
@yjaeseok doesn't have a lot of landed patches, but since v2, he has
actively been reviewing most of PRs.
We believe that they are understand our process well.
ISSUE=none
=> Add @nadongguri and @yjaeseok to CODEOWNERS

client/push/push_manager.ts
Implemented isRegistered function for push api. This function checks
whether the service worker has been successfully installed and the push
notification is subscribed.
ISSUE=none
=> Implement isRegistered for Push API

server/base/application.ts
`application.ts` has a wrong url path.
I fixed it to be the correct path.
ISSUE=none
=> Fixed wrong url

gulpfile.ts
This change fixes the lint command apply to client/ directory as well.
ISSUE=#533
=> Modified lint command to accept multiple arguments

gulpfile.ts
Color is missing after using child_process.exec() function.
Change it to spawn() function to inherit parent stdio.
ISSUE=none
=> Apply color on test result log

server/base/application.ts, server/push/push.router.ts, server/push/push.test.ts
To avoid conflict, updated the skeleton codes again at the most recent
commit phase.
ISSUE=#500
=> Implement skeleton codes in server/push

docs/code_review.md, docs/contributing.md
There are some typo error in document
ISSUE=none
=> Fix typo error in document
